// <auto-generated />
namespace VCHeathCare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingAppointments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingAppointments));
        
        string IMigrationMetadata.Id
        {
            get { return "202010311005502_addingAppointments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
